name: Build Base Static
on: workflow_dispatch

jobs:
  build-static-amd64:
    name: Build AMD64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          make base-static-amd64
          make base-static-tar-amd64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-static-amd64
          path: image-static-amd64.tar

  build-static-arm64:
    name: Build ARM64
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:qemu-v5.2.0
          platforms: arm64

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          make base-static-arm64 || base-static-arm64
          make base-static-tar-arm64

      - name: Upload image to artifact
        uses: actions/upload-artifact@v2
        with:
          name: image-static-arm64
          path: image-static-arm64.tar


  push:
    needs:
      - build-static-arm64
      - build-static-amd64
    name: push
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image-static-amd64

      - name: Download image
        uses: actions/download-artifact@v2
        with:
          name: image-static-arm64

      - name: Load Image
        run: |
          docker load --input image-static-amd64.tar
          docker load --input image-static-arm64.tar

      - name: Push
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker push etcdnecx/ovs-ovn-static:$TAG-amd64
          docker push etcdnecx/ovs-ovn-static:$TAG-arm64
          docker manifest create etcdnecx/ovs-ovn-static:$TAG etcdnecx/ovs-ovn-static:$TAG-amd64 etcdnecx/ovs-ovn-static:$TAG-arm64
          docker manifest push etcdnecx/ovs-ovn-static:$TAG
