name: Build arm64 Image
on:
  push:
    branches:
    - master
    - release-*
    paths-ignore:
    - 'docs/**'
    - '**.md'
env:
  REGISTRY: etcdnecx
  RELEASE_TAG: ecx-v1.9.0
  GO_VERSION: '1.17.5'

jobs:
  build:
    name: Build arm64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - uses: actions/setup-go@v3
        with:
          go-version: '${{ env.GO_VERSION }}'
          check-latest: true
        id: go

      - name: Export Go full version
        run: |
          echo "GO_FULL_VER=$(go version | awk '{print $3}')" >> "$GITHUB_ENV"

      - name: Check out kube-ovn
        run: |
          git clone -b $RELEASE_TAG --depth=1 https://github.com/EdgeCloudX/kube-ovn.git
          cp dist/images/Dockerfile kube-ovn/dist/images/Dockerfile -f
          cp dist/images/Makefile kube-ovn/Makefile -f

      - name: Build
        run: |
          cd kube-ovn
          go mod tidy
          go install github.com/securego/gosec/cmd/gosec@latest
          make release-arm || make release-arm

      - name: Push
        if: ${{ contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker images
          docker tag $REGISTRY/kube-ovn:$TAG $REGISTRY/kube-ovn:$TAG-arm
          docker push $REGISTRY/kube-ovn:$TAG-arm
