name: Push Multi Arch Image
on: workflow_dispatch

env:
  REGISTRY: etcdnecx
  RELEASE_TAG: ecx-v1.9.0

jobs:
  build:
    name: Push multi arch images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2

      - name: Push
        if: ${{ github.ref == 'refs/heads/master' || contains(github.ref, 'release') }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT: ${{ github.sha }}
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          cat VERSION
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull $REGISTR/kube-ovn:$TAG-x86
          docker pull $REGISTR/kube-ovn:$TAG-arm
          docker manifest create $REGISTR/kube-ovn:$TAG $REGISTR/kube-ovn:$TAG-x86 $REGISTR/kube-ovn:$TAG-arm
          docker manifest push $REGISTR/kube-ovn:$TAG
